mongodb:
  image: tutum/mongodb
  environment:
    AUTH: 'no'
    MONGODB_DATABASE: seyren

seyren:
  build: .
  ports:
    - "8080:8080"
  links:
    - mongodb
  environment:
    MONGO_URL: mongodb://mongodb:27017/seyren
    SEYREN_URL: http://localhost:8080
    GRAPHITE_URL:
    GRAPHITE_REFRESH: 60000
    GRAPHITE_CONNECTION_REQUEST_TIMEOUT: 300000
    GRAPHITE_CONNECT_TIMEOUT: 300000
    GRAPHITE_SOCKET_TIMEOUT: 300000
    SMTP_HOST: localhost
    SEYREN_LOG_PATH: /var/log/seyren/
